name: Publish qwc-uwsgi-base docker image

on: [push]

jobs:

    build:
      runs-on: ubuntu-latest
      steps:


      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo ::set-output name=alpine_tag::${GITHUB_REF:10}
            echo ::set-output name=ubuntu_tag::${GITHUB_REF:10}
          else
            echo ::set-output name=alpine_tag::latest
            echo ::set-output name=ubuntu_tag::latest
          fi

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish Alpine docker image
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: m2rt/qwc-uwsgi-base
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "${{ steps.get_tag.outputs.alpine_tag }},alpine-${{ steps.get_tag.outputs.alpine_tag }}"
          workdir: alpine
          platforms: linux/amd64,linux/arm64

      - name: Build and publish Ubuntu docker image
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: m2rt/qwc-uwsgi-base
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "ubuntu-${{ steps.get_tag.outputs.ubuntu_tag }}"
          workdir: ubuntu
          platforms: linux/amd64,linux/arm64
